-- MySQL Script generated by MySQL Workbench
-- Thu May 10 22:10:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HRMS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HRMS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HRMS` DEFAULT CHARACTER SET utf8 ;
USE `HRMS` ;

CREATE TABLE `emp_title` (
  `id` int(5) unsigned zerofill NOT NULL AUTO_INCREMENT COMMENT '职称ID',
  `name` varchar(10) NOT NULL COMMENT '职称名',
  `level` int(11) NOT NULL COMMENT '职称级别',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_UNIQUE` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=21 DEFAULT CHARSET=utf8;


CREATE TABLE `admin_info` (
  `id` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT COMMENT '管理员ID',
  `emp_id` int(10) unsigned zerofill NOT NULL COMMENT '管理员员工ID',
  PRIMARY KEY (`id`),
  UNIQUE KEY `emp_id_UNIQUE` (`emp_id`),
  CONSTRAINT `admin_emp` FOREIGN KEY (`emp_id`) REFERENCES `emp_info` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;


CREATE TABLE `com_department` (
  `id` int(4) unsigned zerofill NOT NULL AUTO_INCREMENT COMMENT '部门ID',
  `name` varchar(40) NOT NULL COMMENT '部门名',
  `addr` varchar(50) DEFAULT NULL COMMENT '部门地址',
  `info` varchar(100) DEFAULT '无' COMMENT '部门信息',
  `mgr` int(10) unsigned zerofill NOT NULL COMMENT '部门经理(外键)',
  `phone_number` varchar(11) DEFAULT NULL,
  `parent_dep` int(4) unsigned zerofill DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `Dep_name_UNIQUE` (`name`),
  KEY `mgr_idx` (`mgr`),
  KEY `dep_dep_idx` (`parent_dep`),
  CONSTRAINT `dep_dep` FOREIGN KEY (`parent_dep`) REFERENCES `com_department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `dep_emp` FOREIGN KEY (`mgr`) REFERENCES `emp_info` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=15 DEFAULT CHARSET=utf8;


CREATE TABLE `com_plan` (
  `id` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT COMMENT '招聘计划ID',
  `status` int(10) unsigned zerofill NOT NULL COMMENT '招聘计划状态',
  `post_id` int(10) unsigned zerofill NOT NULL COMMENT '岗位ID(外键)',
  `dep_id` int(4) unsigned zerofill NOT NULL COMMENT '部门ID(外键)',
  `expect_num` int(10) unsigned NOT NULL COMMENT '需求量',
  `finished_num` int(10) unsigned NOT NULL DEFAULT '0' COMMENT '已完成数量',
  `time_start` date NOT NULL COMMENT '开始时间',
  `time_end` date NOT NULL COMMENT '结束时间',
  `time_create` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间',
  `creator_id` int(10) unsigned zerofill NOT NULL COMMENT '创建人ID(外键)',
  `host_id` int(10) unsigned zerofill DEFAULT NULL COMMENT '负责人ID(外键)',
  PRIMARY KEY (`id`),
  KEY `plan_dict_idx` (`status`),
  KEY `plan_post_idx` (`post_id`),
  KEY `plan_dep_idx` (`dep_id`),
  KEY `plan_emp_idx` (`creator_id`),
  KEY `plan_host_idx` (`host_id`),
  CONSTRAINT `plan_creator` FOREIGN KEY (`creator_id`) REFERENCES `emp_info` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `plan_dep` FOREIGN KEY (`dep_id`) REFERENCES `com_department` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `plan_dict` FOREIGN KEY (`status`) REFERENCES `dict_info` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `plan_host` FOREIGN KEY (`host_id`) REFERENCES `emp_info` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `plan_post` FOREIGN KEY (`post_id`) REFERENCES `com_post` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `com_post` (
  `id` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT COMMENT '岗位ID',
  `name` varchar(40) NOT NULL COMMENT '岗位名',
  `level` int(3) NOT NULL COMMENT '岗位级别',
  `post_salary` int(11) NOT NULL COMMENT '岗位薪资',
  `type` int(10) unsigned zerofill NOT NULL COMMENT '岗位类型(字典)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_UNIQUE` (`name`),
  KEY `post_dict_idx` (`type`),
  CONSTRAINT `post_dict` FOREIGN KEY (`type`) REFERENCES `dict_info` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8;


CREATE TABLE `com_posting` (
  `id` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT COMMENT '在职编号',
  `emp_id` int(10) unsigned zerofill NOT NULL COMMENT '员工ID(外键)',
  `dep_id` int(4) unsigned zerofill NOT NULL,
  `post_id` int(10) unsigned zerofill NOT NULL COMMENT '岗位ID(外键)',
  `status` int(10) unsigned zerofill NOT NULL COMMENT '在职状态(字典)',
  PRIMARY KEY (`id`),
  KEY `posting_post_idx` (`post_id`),
  KEY `posting_dict_idx` (`status`),
  KEY `posting_dep_idx` (`dep_id`),
  KEY `posting_emp` (`emp_id`),
  CONSTRAINT `posting_dep` FOREIGN KEY (`dep_id`) REFERENCES `com_department` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `posting_dict` FOREIGN KEY (`status`) REFERENCES `dict_info` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `posting_emp` FOREIGN KEY (`emp_id`) REFERENCES `emp_info` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `posting_post` FOREIGN KEY (`post_id`) REFERENCES `com_post` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=8 DEFAULT CHARSET=utf8;


CREATE TABLE `dict_info` (
  `id` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT COMMENT '字典项ID',
  `dict_code` varchar(20) NOT NULL COMMENT '查询码',
  `value` varchar(50) NOT NULL COMMENT '字典项值',
  `type_id` int(5) unsigned zerofill NOT NULL COMMENT '所属字典类型ID(外键)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `dict_code_UNIQUE` (`dict_code`),
  KEY `dict_type_idx` (`type_id`),
  CONSTRAINT `dict_type` FOREIGN KEY (`type_id`) REFERENCES `dict_type` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=71 DEFAULT CHARSET=utf8;


CREATE TABLE `dict_type` (
  `id` int(5) unsigned zerofill NOT NULL AUTO_INCREMENT COMMENT '字典类型ID',
  `name` varchar(40) NOT NULL COMMENT '类型名',
  `parent_id` int(5) unsigned zerofill DEFAULT NULL COMMENT '父字典类型ID(外键)',
  PRIMARY KEY (`id`),
  UNIQUE KEY `name_UNIQUE` (`name`),
  KEY `parent_id_idx` (`parent_id`),
  CONSTRAINT `type_type` FOREIGN KEY (`parent_id`) REFERENCES `dict_type` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8;


CREATE TABLE `emp_info` (
  `id` int(10) unsigned zerofill NOT NULL COMMENT '员工ID',
  `password` char(60) NOT NULL COMMENT '用户密码',
  `email` varchar(30) NOT NULL COMMENT '注册email',
  `phone_number` char(11) NOT NULL COMMENT '电话号码',
  `name` varchar(20) NOT NULL COMMENT '员工姓名',
  `birthday` date NOT NULL COMMENT '生日',
  `time_register` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '注册时间',
  `political` int(10) unsigned zerofill NOT NULL COMMENT '政治面貌(字典)',
  `health` int(10) unsigned zerofill NOT NULL COMMENT '健康状况(字典)',
  `title` int(5) unsigned zerofill DEFAULT NULL COMMENT '职称(外键)',
  `bonus` int(10) NOT NULL DEFAULT '0' COMMENT '奖金',
  PRIMARY KEY (`id`),
  UNIQUE KEY `email_UNIQUE` (`email`),
  UNIQUE KEY `phone_number_UNIQUE` (`phone_number`),
  KEY `emp_title_idx` (`title`),
  KEY `emp_dict_idx` (`political`),
  KEY `emp_dict_health_idx` (`health`),
  CONSTRAINT `emp_dict_health` FOREIGN KEY (`health`) REFERENCES `dict_info` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `emp_dict_political` FOREIGN KEY (`political`) REFERENCES `dict_info` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE,
  CONSTRAINT `emp_title` FOREIGN KEY (`title`) REFERENCES `emp_title` (`id`) ON DELETE NO ACTION ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `log_attendence` (
  `id` int(15) unsigned zerofill NOT NULL AUTO_INCREMENT COMMENT '出勤记录ID',
  `date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '考勤时间',
  `emp_id` int(10) unsigned zerofill NOT NULL COMMENT '考勤员工',
  `type` int(10) unsigned zerofill NOT NULL COMMENT '考勤类型(字典)',
  `ip` varchar(30) NOT NULL,
  `value` int(11) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `attendence_emp_idx` (`emp_id`),
  KEY `attendece_type_idx` (`type`),
  CONSTRAINT `attendece_type` FOREIGN KEY (`type`) REFERENCES `dict_info` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `attendence_emp` FOREIGN KEY (`emp_id`) REFERENCES `emp_info` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `log_issue` (
  `id` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT,
  `emp_id` int(10) unsigned zerofill NOT NULL COMMENT '员工ID',
  `type` int(10) unsigned zerofill NOT NULL,
  `subject` varchar(40) NOT NULL,
  `name` varchar(20) NOT NULL,
  `contact` varchar(11) NOT NULL,
  `content` varchar(140) DEFAULT NULL,
  `status` int(10) unsigned zerofill NOT NULL,
  `processor_id` int(10) unsigned zerofill DEFAULT NULL,
  `time_submit` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `emp_id_id` bigint(20) DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `issue_dict_idx` (`type`),
  KEY `issue_emp_idx` (`processor_id`),
  KEY `issue_dict_status_idx` (`status`),
  KEY `issue_emp_id_idx` (`emp_id`),
  CONSTRAINT `issue_dict_status` FOREIGN KEY (`status`) REFERENCES `dict_info` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `issue_dict_type` FOREIGN KEY (`type`) REFERENCES `dict_info` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `issue_emp` FOREIGN KEY (`processor_id`) REFERENCES `emp_info` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `issue_emp_id` FOREIGN KEY (`emp_id`) REFERENCES `emp_info` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;


CREATE TABLE `log_login` (
  `id` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT COMMENT '登录记录ID',
  `emp_id` int(10) unsigned zerofill NOT NULL COMMENT '登录员工ID',
  `ip` varchar(30) NOT NULL COMMENT '登录IP',
  `login_time` time NOT NULL COMMENT '登录时间',
  `logout_time` time NOT NULL COMMENT '断开时间',
  `is_admin` tinyint(4) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `login_emp_idx` (`emp_id`),
  CONSTRAINT `login_emp` FOREIGN KEY (`emp_id`) REFERENCES `emp_info` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


CREATE TABLE `log_post` (
  `id` int(10) unsigned zerofill NOT NULL AUTO_INCREMENT COMMENT '任职记录ID',
  `emp_id` int(10) unsigned zerofill NOT NULL COMMENT '员工ID(外键)',
  `post_type` int(10) unsigned zerofill NOT NULL COMMENT '任职类型(字典)',
  `from_dep_id` int(4) unsigned zerofill DEFAULT NULL COMMENT '调离部门ID(外键)',
  `to_dep_id` int(4) unsigned zerofill DEFAULT NULL COMMENT '调任部门(外键)',
  `from_post_id` int(10) unsigned zerofill DEFAULT NULL COMMENT '调离岗位ID(外键)',
  `to_post_id` int(10) unsigned zerofill DEFAULT NULL COMMENT '调任岗位ID(外键)',
  `applicant_id` int(10) unsigned zerofill NOT NULL COMMENT '申请人ID(外键)',
  `reviewer_id` int(10) unsigned zerofill NOT NULL COMMENT '审核人ID(外键)',
  `plan_id` int(10) unsigned zerofill DEFAULT NULL COMMENT '所属招聘计划ID(外键)',
  `post_time` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '变动时间',
  `post_info` varchar(100) NOT NULL DEFAULT '无' COMMENT '变动信息',
  PRIMARY KEY (`id`),
  KEY `log_post_emp_idx` (`emp_id`),
  KEY `log_post_post_idx` (`from_post_id`),
  KEY `log_post_dep_idx` (`from_dep_id`),
  KEY `log_post_plan_idx` (`plan_id`),
  KEY `log_post_type_idx` (`post_type`),
  KEY `log_post_aplicant_idx` (`applicant_id`),
  KEY `log_post_reviewer_idx` (`reviewer_id`),
  KEY `log_post_post_to_idx` (`to_post_id`),
  KEY `log_post_dep_to_idx` (`to_dep_id`),
  CONSTRAINT `log_post_aplicant` FOREIGN KEY (`applicant_id`) REFERENCES `emp_info` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `log_post_dep_from` FOREIGN KEY (`from_dep_id`) REFERENCES `com_department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `log_post_dep_to` FOREIGN KEY (`to_dep_id`) REFERENCES `com_department` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `log_post_emp` FOREIGN KEY (`emp_id`) REFERENCES `emp_info` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `log_post_plan` FOREIGN KEY (`plan_id`) REFERENCES `com_plan` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `log_post_post_from` FOREIGN KEY (`from_post_id`) REFERENCES `com_post` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `log_post_post_to` FOREIGN KEY (`to_post_id`) REFERENCES `com_post` (`id`) ON DELETE SET NULL ON UPDATE CASCADE,
  CONSTRAINT `log_post_reviewer` FOREIGN KEY (`reviewer_id`) REFERENCES `emp_info` (`id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `log_post_type` FOREIGN KEY (`post_type`) REFERENCES `dict_info` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;;

CREATE 
    ALGORITHM = MERGE 
    DEFINER = `root`@`%` 
    SQL SECURITY DEFINER
VIEW `HRMS`.`view_emp_info` AS
    SELECT 
        `HRMS`.`emp_info`.`id` AS `emp_id`,
        `HRMS`.`emp_info`.`name` AS `emp_name`,
        `HRMS`.`com_post`.`name` AS `post_name`,
        `HRMS`.`com_department`.`name` AS `dep_name`,
        `HRMS`.`emp_title`.`name` AS `title_name`,
        `HRMS`.`emp_info`.`email` AS `email`,
        `HRMS`.`emp_info`.`phone_number` AS `phone_number`,
        `HRMS`.`emp_info`.`birthday` AS `birthday`,
        `HRMS`.`emp_info`.`time_register` AS `time_register`,
        `dict_info_1`.`value` AS `political_value`,
        `dict_info_2`.`value` AS `health_value`
    FROM
        ((((((`HRMS`.`emp_info`
        LEFT JOIN `HRMS`.`emp_title` ON ((`HRMS`.`emp_info`.`title` = `HRMS`.`emp_title`.`id`)))
        JOIN `HRMS`.`com_department`)
        JOIN `HRMS`.`com_post`)
        JOIN `HRMS`.`com_posting`)
        JOIN `HRMS`.`dict_info` `dict_info_1`)
        JOIN `HRMS`.`dict_info` `dict_info_2`)
    WHERE
        ((`HRMS`.`emp_info`.`id` = `HRMS`.`com_posting`.`emp_id`)
            AND (`HRMS`.`com_posting`.`dep_id` = `HRMS`.`com_department`.`id`)
            AND (`HRMS`.`emp_info`.`political` = `dict_info_1`.`id`)
            AND (`HRMS`.`emp_info`.`health` = `dict_info_2`.`id`)
            AND (`HRMS`.`com_posting`.`post_id` = `HRMS`.`com_post`.`id`))

CREATE 
    ALGORITHM = UNDEFINED 
    DEFINER = `root`@`%` 
    SQL SECURITY DEFINER
VIEW `HRMS`.`view_dep_info` AS
    SELECT 
        `dep1`.`id` AS `dep_id`,
        `dep1`.`name` AS `dep_name`,
        `HRMS`.`emp_info`.`name` AS `mgr_name`,
        `dep1`.`phone_number` AS `dep_number`,
        `dep1`.`addr` AS `addr`,
        `dep1`.`info` AS `info`,
        `dep2`.`name` AS `parent_dep_name`
    FROM
        ((`HRMS`.`com_department` `dep1`
        LEFT JOIN `HRMS`.`com_department` `dep2` ON ((`dep1`.`parent_dep` = `dep2`.`id`)))
        JOIN `HRMS`.`emp_info`)
    WHERE
        (`dep1`.`mgr` = `HRMS`.`emp_info`.`id`)
		
CREATE 
    ALGORITHM = MERGE 
    DEFINER = `root`@`%` 
    SQL SECURITY DEFINER
VIEW `HRMS`.`view_emp_salary` AS
    SELECT 
        `HRMS`.`emp_info`.`id` AS `emp_id`,
        `HRMS`.`emp_info`.`name` AS `emp_name`,
        `HRMS`.`com_post`.`name` AS `post_name`,
        `HRMS`.`com_post`.`post_salary` AS `post_salary_month`,
        `HRMS`.`emp_info`.`bonus` AS `year_bonus`
    FROM
        ((`HRMS`.`com_posting`
        JOIN `HRMS`.`com_post`)
        LEFT JOIN `HRMS`.`emp_info` ON ((`HRMS`.`com_posting`.`emp_id` = `HRMS`.`emp_info`.`id`)))
    WHERE
        (`HRMS`.`com_posting`.`post_id` = `HRMS`.`com_post`.`id`)

CREATE USER 'hr_system' IDENTIFIED BY 'nmklp666';

GRANT SELECT ON TABLE `HRMS`.* TO 'hr_system';
GRANT SHOW VIEW, SELECT ON TABLE `HRMS`.`view_dep_info` TO 'hr_system';
GRANT SHOW VIEW, INSERT ON TABLE `HRMS`.`view_emp_info` TO 'hr_system';
CREATE USER 'admins' IDENTIFIED BY 'nmklp666+';

GRANT ALL ON `HRMS`.* TO 'admins';
GRANT ALL ON TABLE `HRMS`.`view_dep_info` TO 'admins';
GRANT ALL ON TABLE `HRMS`.`view_emp_info` TO 'admins';
CREATE USER 'visitor' IDENTIFIED BY 'nmklp666';

grant select on HRMS.com_department to hr_system@'localhost';
grant select on HRMS.com_plan to hr_system@'localhost';
grant select on HRMS.com_post to hr_system@'localhost';
grant select on HRMS.com_posting to hr_system@'localhost';
grant select on HRMS.dict_info to hr_system@'localhost';
grant select on HRMS.dict_type to hr_system@'localhost';
grant select on HRMS.emp_info to hr_system@'localhost';
grant select on HRMS.emp_title to hr_system@'localhost';
grant select, insert  on HRMS.log_attendence to hr_system@'localhost';
grant select on HRMS.log_login to hr_system@'localhost';
grant select on HRMS.log_post to hr_system@'localhost';

grant insert on HRMS.log_issue to visitor@'localhost';

grant show view on HRMS.view_dep_info to hr_system@'localhost';
grant show view on HRMS.view_emp_info to hr_system@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
