-- MySQL Script generated by MySQL Workbench
-- Wed May  9 14:50:42 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HRAS
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HRAS
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HRAS` DEFAULT CHARACTER SET utf8 ;
USE `HRAS` ;

-- -----------------------------------------------------
-- Table `HRAS`.`emp_title`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HRAS`.`emp_title` (
  `name` VARCHAR(10) NOT NULL,
  `level` INT NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HRAS`.`dict_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HRAS`.`dict_type` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `code` VARCHAR(10) NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `parent_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `parent_id_idx` (`parent_id` ASC),
  CONSTRAINT `type_type`
    FOREIGN KEY (`parent_id`)
    REFERENCES `HRAS`.`dict_type` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HRAS`.`dict_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HRAS`.`dict_info` (
  `id` INT(10) ZEROFILL NOT NULL,
  `value` VARCHAR(50) NOT NULL,
  `type_id` INT NOT NULL,
  `dict_code` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `type_id_idx` (`type_id` ASC),
  UNIQUE INDEX `dict_code_UNIQUE` (`dict_code` ASC),
  CONSTRAINT `dict_type`
    FOREIGN KEY (`type_id`)
    REFERENCES `HRAS`.`dict_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HRAS`.`emp_info`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HRAS`.`emp_info` (
  `id` INT(10) ZEROFILL NOT NULL,
  `password` CHAR(32) NOT NULL,
  `email` VARCHAR(30) NOT NULL,
  `phone_number` CHAR(11) NOT NULL,
  `name` VARCHAR(20) NOT NULL,
  `birthday` DATE NOT NULL,
  `time_register` TIMESTAMP NOT NULL,
  `political` VARCHAR(20) NOT NULL,
  `health` VARCHAR(20) NOT NULL,
  `title` VARCHAR(10) NOT NULL,
  `dep_id` INT(4) ZEROFILL NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC),
  INDEX `dep_id_idx` (`dep_id` ASC),
  INDEX `emp_title_idx` (`title` ASC),
  INDEX `emp_dict_idx` (`political` ASC, `health` ASC),
  CONSTRAINT `emp_dep`
    FOREIGN KEY (`dep_id`)
    REFERENCES `HRAS`.`com_department` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `emp_title`
    FOREIGN KEY (`title`)
    REFERENCES `HRAS`.`emp_title` (`name`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `emp_dict`
    FOREIGN KEY (`political` , `health`)
    REFERENCES `HRAS`.`dict_info` (`dict_code` , `dict_code`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HRAS`.`com_department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HRAS`.`com_department` (
  `id` INT(4) ZEROFILL NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `addr` VARCHAR(50) NULL,
  `info` VARCHAR(100) NULL DEFAULT '无',
  `mgr` INT(10) ZEROFILL NOT NULL,
  `parent_dep_id` INT(4) ZEROFILL NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `Dep_id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `Dep_name_UNIQUE` (`name` ASC),
  INDEX `mgr_idx` (`mgr` ASC),
  INDEX `parent_dep_idx` (`parent_dep_id` ASC),
  CONSTRAINT `dep_emp`
    FOREIGN KEY (`mgr`)
    REFERENCES `HRAS`.`emp_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `dep_dep`
    FOREIGN KEY (`parent_dep_id`)
    REFERENCES `HRAS`.`com_department` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HRAS`.`com_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HRAS`.`com_post` (
  `id` INT NOT NULL,
  `name` VARCHAR(40) NOT NULL,
  `level` INT(3) NOT NULL,
  `post_salary` INT NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  INDEX `post_dict_idx` (`type` ASC),
  CONSTRAINT `post_dict`
    FOREIGN KEY (`type`)
    REFERENCES `HRAS`.`dict_info` (`dict_code`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HRAS`.`com_posting`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HRAS`.`com_posting` (
  `emp_id` INT(10) NOT NULL,
  `post_id` INT NOT NULL,
  `status` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`emp_id`, `post_id`),
  INDEX `posting_post_idx` (`post_id` ASC),
  INDEX `posting_dict_idx` (`status` ASC),
  CONSTRAINT `posting_emp`
    FOREIGN KEY (`emp_id`)
    REFERENCES `HRAS`.`emp_info` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `posting_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `HRAS`.`com_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `posting_dict`
    FOREIGN KEY (`status`)
    REFERENCES `HRAS`.`dict_info` (`dict_code`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HRAS`.`com_plan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HRAS`.`com_plan` (
  `id` INT(10) ZEROFILL NOT NULL AUTO_INCREMENT,
  `status` VARCHAR(20) NOT NULL,
  `post_id` INT NOT NULL,
  `dep_id` INT(4) NOT NULL,
  `expect_num` INT NOT NULL,
  `time_start` DATE NOT NULL,
  `time_end` DATE NOT NULL,
  `time_create` TIMESTAMP NOT NULL,
  `creator_id` INT(10) NOT NULL,
  `host_id` INT(10) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `plan_dict_idx` (`status` ASC),
  INDEX `plan_post_idx` (`post_id` ASC),
  INDEX `plan_dep_idx` (`dep_id` ASC),
  INDEX `plan_emp_idx` (`creator_id` ASC, `host_id` ASC),
  CONSTRAINT `plan_dict`
    FOREIGN KEY (`status`)
    REFERENCES `HRAS`.`dict_info` (`dict_code`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE,
  CONSTRAINT `plan_post`
    FOREIGN KEY (`post_id`)
    REFERENCES `HRAS`.`com_post` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `plan_dep`
    FOREIGN KEY (`dep_id`)
    REFERENCES `HRAS`.`com_department` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `plan_emp`
    FOREIGN KEY (`creator_id` , `host_id`)
    REFERENCES `HRAS`.`emp_info` (`id` , `id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HRAS`.`log_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HRAS`.`log_post` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emp_id` INT(10) NOT NULL,
  `post_type` VARCHAR(20) NULL,
  `from_dep_id` INT(4) NULL,
  `from_post_id` INT NULL,
  `to_post_id` INT NULL,
  `to_dep_id` INT(4) NULL,
  `applicant_id` INT(10) NOT NULL,
  `reviewer_id` INT(10) NOT NULL,
  `plan_id` INT(10) NULL,
  `post_time` TIMESTAMP NOT NULL,
  `post_info` VARCHAR(100) NOT NULL DEFAULT '无',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `log_post_emp_idx` (`emp_id` ASC, `applicant_id` ASC, `reviewer_id` ASC),
  INDEX `log_post_post_idx` (`from_post_id` ASC, `to_post_id` ASC),
  INDEX `log_post_dep_idx` (`from_dep_id` ASC, `to_dep_id` ASC),
  INDEX `log_post_plan_idx` (`plan_id` ASC),
  CONSTRAINT `log_post_emp`
    FOREIGN KEY (`emp_id` , `applicant_id` , `reviewer_id`)
    REFERENCES `HRAS`.`emp_info` (`id` , `id` , `id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `log_post_post`
    FOREIGN KEY (`from_post_id` , `to_post_id`)
    REFERENCES `HRAS`.`com_post` (`id` , `id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `log_post_dep`
    FOREIGN KEY (`from_dep_id` , `to_dep_id`)
    REFERENCES `HRAS`.`com_department` (`id` , `id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `log_post_plan`
    FOREIGN KEY (`plan_id`)
    REFERENCES `HRAS`.`com_plan` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HRAS`.`log_attendence`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HRAS`.`log_attendence` (
  `id` INT(10) ZEROFILL NOT NULL,
  `date` TIMESTAMP NOT NULL,
  `emp_id` INT(10) NOT NULL,
  `info` VARCHAR(50) NOT NULL,
  `value` INT NOT NULL DEFAULT 0,
  `type` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `attendence_emp_idx` (`emp_id` ASC),
  INDEX `attendece_type_idx` (`type` ASC),
  CONSTRAINT `attendence_emp`
    FOREIGN KEY (`emp_id`)
    REFERENCES `HRAS`.`emp_info` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `attendece_type`
    FOREIGN KEY (`type`)
    REFERENCES `HRAS`.`dict_info` (`dict_code`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `HRAS`.`log_login`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `HRAS`.`log_login` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emp_id` INT(10) NOT NULL,
  `ip` VARCHAR(30) NOT NULL,
  `login_time` TIME NOT NULL,
  `logout_time` TIME NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `login_emp_idx` (`emp_id` ASC),
  CONSTRAINT `login_emp`
    FOREIGN KEY (`emp_id`)
    REFERENCES `HRAS`.`emp_info` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;

CREATE USER 'hr_system' IDENTIFIED BY 'nmklp666';

GRANT ALL ON `HRAS`.* TO 'hr_system';
GRANT SELECT ON TABLE `HRAS`.* TO 'hr_system';
GRANT SELECT, INSERT, TRIGGER ON TABLE `HRAS`.* TO 'hr_system';
GRANT SELECT, INSERT, TRIGGER, UPDATE, DELETE ON TABLE `HRAS`.* TO 'hr_system';
GRANT EXECUTE ON ROUTINE `HRAS`.* TO 'hr_system';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
